#! /bin/sh -
#
# Copyright (C) Stealth Software Technologies, Inc.
#
# For the complete copyright information, please see the
# associated README file.
#
# This script uses the SST Bash library to bootstrap from /bin/sh into
# bash. See the Bash library > Bootstrapping section of the SST manual
# for more information.
#

#-----------------------------------------------------------------------
# Include the SST Bash library
#-----------------------------------------------------------------------

set -e || exit $?
if test -f sst.bash; then
  . ./sst.bash
else
  . sst.bash
fi

#-----------------------------------------------------------------------

if ! command -v sudo >/dev/null; then
  echo "Installing sudo with yum..."
  su -c "yum install -y sudo" root
fi

echo "Installing various packages with yum..."
sudo bash -c ': \
  && yum -y install epel-release \
  && yum -y install \
    diffutils \
    gcc \
    gcc-c++ \
    git \
    make \
    nettle-devel \
    openssl \
    sshpass \
    texinfo \
  && : \
;'

./configure \
;

echo "Installing PFSS..."
sudo make install

echo "Running ldconfig..."
sudo ldconfig
