#! /bin/sh -
#
# For the copyright information for this file, please search up the
# directory tree for the first COPYING file.
#
# This script uses the SST Bash library to bootstrap from /bin/sh into
# bash. See the Bash library > Bootstrapping section of the SST manual
# for more information.
#

# Load the prelude.
case $0 in /*) x=$0 ;; *) x=./$0 ;; esac
r='\(.*/\)'
x=`expr "$x" : "$r"` || exit $?
set -e || exit $?
. "$x"../../prelude.bash

dist_archive=$rundir/$(sst_find_dist_archive)
readonly dist_archive

cd "$tmpdir"
sst_extract_archive "$dist_archive"
cd *
install/on-ubuntu
make V=1 VERBOSE=1 distcheck
