#! /bin/sh -
#
# Usage: adock [<arg>...]
#
# Runs an asciidoctor/docker-asciidoctor container with the given
# arguments. The current working directory will be mapped into and used
# as the current working directory in the container. The container will
# inherit the current user and group IDs so that any files it produces
# will have the appropriate ownership.
#
# See <https://hub.docker.com/r/asciidoctor/docker-asciidoctor> for more
# information about the asciidoctor/docker-asciidoctor image.
#
# You can change the docker command by setting the DOCKER environment
# variable. The value will be evaluated by the shell.
#
# You can change the container image by setting the ADOCK_IMAGE
# environment variable.
#
# You can force the newest container image to be pulled by setting the
# ADOCK_PULL environment variable to any nonempty value.
#
# Example 1:
#
# The following command will compile README.adoc into README.html:
#
#       adock asciidoctor README.adoc
#
# Example 2:
#
# The following command will compile README.adoc into README.pdf:
#
#       adock asciidoctor-pdf README.adoc
#
# Example 3:
#
# The following command will compile README.adoc into README.html,
# running docker with sudo:
#
#       DOCKER='sudo docker' adock asciidoctor README.adoc
#

export LC_ALL=C

docker=" ${DOCKER:-docker}"
readonly docker

image=${ADOCK_IMAGE:-asciidoctor/docker-asciidoctor}
readonly image

[ -t 0 ] && t=-t || t=
u=`id -u` || exit $?
g=`id -g` || exit $?
pwd=`pwd` || exit $?
if ${ADOCK_PULL:+:} false; then
  eval "$docker"' pull "$image"' || exit $?
fi
args='run --rm -i $t -u $u:$g -v "$pwd":/x -w /x "$image"'
case $# in
  0)
    eval "$docker $args"
    exit $?
  ;;
  *)
    eval "$docker $args"' "$@"'
    exit $?
  ;;
esac

#
# The authors of this file have waived all copyright and
# related or neighboring rights to the extent permitted by
# law as described by the CC0 1.0 Universal Public Domain
# Dedication. You should have received a copy of the full
# dedication along with this file, typically as a file
# named <CC0-1.0.txt>. If not, it may be available at
# <https://creativecommons.org/publicdomain/zero/1.0/>.
#
