/*
 * This file was generated by GATBPS 0.1.0-5652+ge41a2cc3, which was
 * released on 2021-04-21. Before changing it, make sure
 * you're doing the right thing. Depending on how GATBPS
 * is being used, your changes may be automatically lost.
 * A short description of this file follows.
 *
 * Special file: TEST_EXIT.h
 *
 * The TEST_EXIT.h special file is a C header file that defines the
 * TEST_EXIT_ERROR, TEST_EXIT_FAIL, TEST_EXIT_PASS, and TEST_EXIT_SKIP
 * macros to 99, 1, 0, and 77, respectively. These are the exit status
 * values used by GNU Automake for a test suite with no test protocol.
 *
 * For more information, see the GATBPS manual.
 */

/**
 * @file
 */

/**
 *
 * @showinitializer
 */

#if (!defined(TEST_EXIT_ERROR))
  #define TEST_EXIT_ERROR 99
#endif

/**
 *
 * @showinitializer
 */

#if (!defined(TEST_EXIT_FAIL))
  #define TEST_EXIT_FAIL 1
#endif

/**
 *
 * @showinitializer
 */

#if (!defined(TEST_EXIT_PASS))
  #define TEST_EXIT_PASS 0
#endif

/**
 *
 * @showinitializer
 */

#if (!defined(TEST_EXIT_SKIP))
  #define TEST_EXIT_SKIP 77
#endif

/*
 * The authors of this file have waived all copyright and
 * related or neighboring rights to the extent permitted by
 * law as described by the CC0 1.0 Universal Public Domain
 * Dedication. You should have received a copy of the full
 * dedication along with this file, typically as a file
 * named <CC0-1.0.txt>. If not, it may be available at
 * <https://creativecommons.org/publicdomain/zero/1.0/>.
 */
