#
# Copyright (C) Stealth Software Technologies, Inc.
#
# For the complete copyright information, please see the
# associated README file.
#

#
# sst_ajh_c_cpp_test <dir> <lib>...
#

sst_ajh_c_cpp_test() {

  local dir
  local libs
  local x1
  local x2
  local x3

  sst_expect_argument_count $# 2-

  dir=$1
  readonly dir
  shift

  libs=$@
  readonly libs

  sst_am_distribute $dir/**/*.@(h|hpp)

  for x1 in \
    $dir/**/*.c \
    $dir/**/*.cpp \
  ; do

    expect_safe_path "$x1"

    x2=$(echo $x1 | sed 's/\.[^.]*$//')
    x3=$(echo $x2 | sed 's/[^A-Za-z0-9_]/_/g')

    cat >$x2.gitignorable.am <<EOF
##
## Copyright (C) Stealth Software Technologies, Inc.
##
## For the complete copyright information, please see the
## associated README file.
##

##
## This file was generated by ./autogen.
##

## begin_variables

TESTS += $x2

check_PROGRAMS += $x2

${x3}_CFLAGS = \\
  \$(AM_CFLAGS) \\
  \$(EXE_CFLAGS) \\
\$(empty)

${x3}_CPPFLAGS = \\
  \$(AM_CPPFLAGS) \\
  -I $dir \\
  -I \$(srcdir)/$dir \\
\$(empty)

${x3}_CXXFLAGS = \\
  \$(AM_CXXFLAGS) \\
  \$(EXE_CXXFLAGS) \\
\$(empty)

${x3}_LDADD = $libs

${x3}_LDFLAGS = \\
  \$(AM_LDFLAGS) \\
  \$(EXE_LDFLAGS) \\
\$(empty)

${x3}_SOURCES = $x1

## end_variables
EOF

    sst_am_include $x2.gitignorable.am

  done

}; readonly -f sst_ajh_c_cpp_test
