#
# Copyright (C) Stealth Software Technologies, Inc.
#
# For the complete copyright information, please see the
# associated README file.
#

exclude:
  - '*.ac'
  - '*.ag'
  - '*.am'
  - '*.in'
  - '*.out'
  - Gemfile
  - Gemfile.lock

sass:
  sourcemap: never
