#! /bin/sh -
#
# Copyright (C) Stealth Software Technologies, Inc.
#
# For the complete copyright information, please see the
# associated README file.
#

#
# All install/* scripts should be identical copies of each other. Do not
# change them into symbolic links to one master copy, as symbolic links
# may not be supported by all environments supported by this script.
#

if test -f src/install/on-x; then
  :
else
  cat <<EOF >&2
$0: Error: You must run this script from the root of the project.
EOF
  exit 1
fi

case $# in 0)
  exec src/install/on-x "$0" || exit $?
;; *)
  exec src/install/on-x "$0" "$@" || exit $?
esac
