#! /bin/sh -
#
# Copyright (C) Stealth Software Technologies, Inc.
#
# For the complete copyright information, please see the
# associated README file.
#
# This script uses the SST Bash library to bootstrap from /bin/sh into
# bash. See the Bash library > Bootstrapping section of the SST manual
# for more information.
#

#-----------------------------------------------------------------------
# Include the SST Bash library
#-----------------------------------------------------------------------

set -e || exit $?
if test -f sst.bash; then
  . ./sst.bash
else
  . sst.bash
fi

#-----------------------------------------------------------------------

if ! command -v sudo >/dev/null; then
  echo "Installing sudo with yum..."
  su -c "yum install -y sudo" root
fi

echo "Installing various packages with yum..."
sudo bash -c ': \
  && yum -y install epel-release \
  && dnf -y install "dnf-command(config-manager)" \
  && dnf -y config-manager --set-enabled PowerTools \
  && yum -y install \
    autoconf \
    automake \
    diffutils \
    git \
    jq \
    libtool \
    m4 \
  && : \
;'

./autogen

src/install/from-dist/$on_x
