#! /bin/bash -
#
# For the copyright information for this file, please search up the
# directory tree for the first COPYING file.
#

set -e; . src/bash/preludes/standard.bash

if ! command -v sudo >/dev/null; then
  echo "Installing sudo with yum..."
  su -c "yum install -y sudo" root
fi

echo "Installing various packages with yum..."
sudo bash -c ': \
  && yum -y install epel-release \
  && yum -y install \
    autoconf \
    automake \
    diffutils \
    git \
    jq \
    libtool \
    m4 \
  && : \
;'

./autogen

src/install/from-dist/$on_x
