#! /bin/sh -
#
# Copyright (C) Stealth Software Technologies, Inc.
#
# For the complete copyright information, please see the
# associated README file.
#

#-----------------------------------------------------------------------
# Include the SST Bash library
#-----------------------------------------------------------------------
#
# Include the first sst.bash file found by searching up the directory
# tree starting from the location of this script file. If no such file
# is found, fall back to including plain sst.bash with PATH resolution.
# Use SST_BASH_PRELUDE_PATH to cache the location of the sst.bash file
# to prevent a redundant search from occurring during the bootstrap.
#

case ${SST_BASH_PRELUDE_PATH-} in '')
  case $0 in /*)
    x=$0
  ;; *)
    x=./$0
  esac
  r='\(.*/\)'
  x=`expr "x${x?}" : "x${r?}"`. || exit $?
  SST_BASH_PRELUDE_PATH=`
    cd "${x?}" || exit $?
    while :; do
      if test -f sst.bash; then
        case ${PWD?} in *[!/]*)
          printf '%s\n' "${PWD?}"/sst.bash || exit $?
        ;; *)
          printf '%s\n' "${PWD?}"sst.bash || exit $?
        esac
        exit
      fi
      case ${PWD?} in *[!/]*)
        cd ..
      ;; *)
        printf '%s\n' sst.bash || exit $?
        exit
      esac
    done
  ` || exit $?
  export SST_BASH_PRELUDE_PATH
esac
set -e || exit $?
. "${SST_BASH_PRELUDE_PATH?}"
unset SST_BASH_PRELUDE_PATH

#-----------------------------------------------------------------------

main() {

  sst_ubuntu_install_raw lsb-core

  v=$(lsb_release -r | sed 's/^[^0-9]*//')
  case $v in
    18.0[4-9]* | 18.[1-9]* | 19.* | 20.0[0-3]*)
      v=18.04
    ;;
    20.0[4-9]* | 20.[1-9]* | 21.* | 22.0[0-3]*)
      v=20.04
    ;;
    *)
      sst_barf 'Unsupported Ubuntu version: %s' "$v"
    ;;
  esac
  readonly v

  on_x=on-ubuntu-$v
  export on_x

  s=src/install/$from_w/$on_x
  readonly s

  if [[ ! -f "$s" && ! -h "$s" ]]; then
    sst_barf 'Unsupported Ubuntu version: %s' "$v"
  fi

  "$s" "$@"

}; readonly -f main

main "$@"
