#
# Copyright (C) Stealth Software Technologies, Inc.
#
# For the complete copyright information, please see the
# associated README file.
#

#
# autogen_print_am_header
#

autogen_print_am_header() {

  if (($# != 0)); then
    sst_barf 'invalid argument count: %d' $#
  fi

  cat <<"EOF"
##
## Copyright (C) Stealth Software Technologies, Inc.
##
## For the complete copyright information, please see the
## associated README file.
##

##
## This file was generated by autogen.
##

EOF

}; readonly -f autogen_print_am_header
