//
// For the copyright information for this file, please search up the
// directory tree for the first COPYING file.
//

[[cl_pfss_eval_all_dot,pfss_eval_all_dot]]
= The `pfss_eval_all_dot` function

.C and {cpp}
[source,c]
----
pfss_status pfss_eval_all_dot(
  pfss_key const * const * keys,
  uint32_t                 keys_count,
  uint8_t const *          ys,
  uint32_t                 y_size,
  pfss_endianness          y_endianness,
  uint8_t *                zs,
  uint32_t                 z_size,
  pfss_endianness          z_endianness,
  uint32_t                 thread_count
);
----

The `pfss_eval_all_dot` function evaluates multiple keys over the
complete grid of domain elements and computes the dot product of each
resulting grid with an existing grid.

:fp_keys: `keys`
:fp_keys_count: `keys_count`
include::cl_homogeneous_key_array_fragment.adoc[]

:fp_ys: `ys`
:fp_key: each key
:fp_y_size: `y_size`
:fp_y_endianness: `y_endianness`
:fp_keys_count: `keys_count`
include::cl_complete_grid_fragment.adoc[]

`zs` should point to an array of `keys_count` unsigned integers.
Each unsigned integer should consist of `z_size` bytes in `z_endianness`
byte order.

Each key is evaluated at all domain elements to produce an intermediate
grid.
The dot product of the intermediate grid is taken with `ys`, and the
result is written to the corresponding element of `zs`.
The result is taken modulo stem:[2^r] where stem:[r] is the number of
range bits in each key.

:fp_thread_count: `thread_count`
include::cl_thread_count_parameter_fragment.adoc[]

include::cl_return_status_blurb.adoc[]

include::cl_key_concurrency_blurb.adoc[]

.{empty}
[example]
====
.Program
[source,cpp]
----
include::cl_pfss_eval_all_dot_example_1_program.cpp[]
----

.Possible output
[source]
----
include::cl_pfss_eval_all_dot_example_1_output.txt[]
----
====

//
