//
// For the copyright information for this file, please search up the
// directory tree for the first COPYING file.
//

[[hardware_acceleration]]
= Hardware acceleration

PFSS can optionally be compiled to use special CPU instructions for
increased performance.
The `./configure` step of the build system automatically detects which
of these instructions are available under the specified compiler flags
and enables them in the code accordingly.

The terms _build system_ and _host system_ are generally used to refer
to the system on which you are compiling the code and the system on
which you will be running the compiled code, respectively.
This overloads the term "`build system`", which is also generally used
to refer to the overall build system, but the meaning should be clear
from context.

== x86 acceleration

For the x86 family of CPUs, there is one CPU instruction set that can be
enabled: AES-NI.

You can generally enable AES-NI by adding `-maes` to both `CFLAGS` and
`CXXFLAGS`.
If you're not cross-compiling, it's usually sufficient to specify
`-march=native` without any other `-m` options.

You can also specify `--with-aes-ni` to `./configure` to instruct it to
verify that AES-NI was detected, failing if not.

== ARM acceleration

For the ARM family of CPUs, there is one CPU instruction set that can be
enabled: ARM Crypto.

You can generally enable ARM Crypto by adding `-march=armv8-a+crypto` to
both `CFLAGS` and `CXXFLAGS`.
You can adjust this flag as needed, it is only the `+crypto` extension
that is required.
If you're not cross-compiling, it's usually sufficient to specify
`-march=native` without any other `-m` options.

You can also specify `--with-arm-crypto` to `./configure` to instruct it
to verify that ARM Crypto was detected, failing if not.
