//
// For the copyright information for this file, please search up the
// directory tree for the first COPYING file.
//
[[hardware_acceleration]]
= Hardware acceleration

PFSS can optionally be compiled to use special CPU instructions for
increased performance.
The `./configure` step of the build system automatically detects which
of these instructions are available and enables them in the code
accordingly.
However, the detection process sometimes needs user intervention to
ensure that the instructions are being detected properly.

The terms _build system_ and _host system_ are generally used to refer
to the system on which you are compiling the code and the system on
which you will be running the compiled code, respectively.
This overloads the term "`build system`", which is also generally used
to refer to the overall build system, but the meaning should be clear
from context.

== x86 acceleration

For the x86 family of CPUs, there are two CPU instruction groups that
can be enabled: SSE2 and AES-NI.

If you're not cross compiling, `./configure` is usually able to detect
these instruction groups properly without any user intervention.

:feat: group
:features: instruction groups

include::with_feat_or_die_1.adoc[]

----
--with-sse2-or-die  --with-aes-ni-or-die
----

include::with_feat_or_die_2.adoc[]

----
--with-cross-cflag-msse2  --with-cross-cxxflag-msse2
--with-cross-cflag-maes   --with-cross-cxxflag-maes
----

include::with_feat_or_die_3.adoc[]
For example, since AES-NI cannot be available without SSE2 also being
available, neglecting to specify `--with-cross-cflag-msse2` will cause
`--with-cross-cflag-maes` to have no effect.

== ARM acceleration

For the ARM family of CPUs, there is one CPU instruction group that can
be enabled: ARM Crypto.

Regardless of whether you're cross compiling, `./configure` usually
needs user intervention to detect this instruction group properly.
To do this, specify at least one of the `-march=...` and `--mcpu=...`
options in both `CFLAGS` and `CXXFLAGS` when running `./configure`.

:feat: group
:features: instruction groups

include::with_feat_or_die_1.adoc[]

----
--with-arm-crypto-or-die
----

include::with_feat_or_die_2.adoc[]

----
--with-cross-cflag-march-arm-crypto  --with-cross-cxxflag-march-arm-crypto
----

include::with_feat_or_die_3.adoc[]
